#!/usr/bin/env bash
# Bash script that loops from 1 to 10.

COUNT=1
while [[ $COUNT -lt 11 ]]
do
    if [ $COUNT = 4 ]
    then
        echo "bad luck"
    elif [ $COUNT = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    COUNT=$(( COUNT+1 ))
done
